// Generated by gencpp from file robot_local_control/GaitechBool.msg
// DO NOT EDIT!


#ifndef ROBOT_LOCAL_CONTROL_MESSAGE_GAITECHBOOL_H
#define ROBOT_LOCAL_CONTROL_MESSAGE_GAITECHBOOL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_local_control
{
template <class ContainerAllocator>
struct GaitechBool_
{
  typedef GaitechBool_<ContainerAllocator> Type;

  GaitechBool_()
    : data(false)  {
    }
  GaitechBool_(const ContainerAllocator& _alloc)
    : data(false)  {
  (void)_alloc;
    }



   typedef uint8_t _data_type;
  _data_type data;




  typedef boost::shared_ptr< ::robot_local_control::GaitechBool_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_local_control::GaitechBool_<ContainerAllocator> const> ConstPtr;

}; // struct GaitechBool_

typedef ::robot_local_control::GaitechBool_<std::allocator<void> > GaitechBool;

typedef boost::shared_ptr< ::robot_local_control::GaitechBool > GaitechBoolPtr;
typedef boost::shared_ptr< ::robot_local_control::GaitechBool const> GaitechBoolConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_local_control::GaitechBool_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_local_control::GaitechBool_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot_local_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'robot_local_control': ['/home/fetch/catkin_ws/src/robot_local_control/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robot_local_control::GaitechBool_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_local_control::GaitechBool_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_local_control::GaitechBool_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_local_control::GaitechBool_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_local_control::GaitechBool_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_local_control::GaitechBool_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_local_control::GaitechBool_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8b94c1b53db61fb6aed406028ad6332a";
  }

  static const char* value(const ::robot_local_control::GaitechBool_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8b94c1b53db61fb6ULL;
  static const uint64_t static_value2 = 0xaed406028ad6332aULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_local_control::GaitechBool_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_local_control/GaitechBool";
  }

  static const char* value(const ::robot_local_control::GaitechBool_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_local_control::GaitechBool_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool data\n\
";
  }

  static const char* value(const ::robot_local_control::GaitechBool_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_local_control::GaitechBool_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GaitechBool_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_local_control::GaitechBool_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_local_control::GaitechBool_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_LOCAL_CONTROL_MESSAGE_GAITECHBOOL_H
