// Generated by gencpp from file robot_local_control/GaitechPose.msg
// DO NOT EDIT!


#ifndef ROBOT_LOCAL_CONTROL_MESSAGE_GAITECHPOSE_H
#define ROBOT_LOCAL_CONTROL_MESSAGE_GAITECHPOSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_local_control
{
template <class ContainerAllocator>
struct GaitechPose_
{
  typedef GaitechPose_<ContainerAllocator> Type;

  GaitechPose_()
    : locationX(0.0)
    , locationY(0.0)
    , orientation(0.0)  {
    }
  GaitechPose_(const ContainerAllocator& _alloc)
    : locationX(0.0)
    , locationY(0.0)
    , orientation(0.0)  {
  (void)_alloc;
    }



   typedef double _locationX_type;
  _locationX_type locationX;

   typedef double _locationY_type;
  _locationY_type locationY;

   typedef double _orientation_type;
  _orientation_type orientation;




  typedef boost::shared_ptr< ::robot_local_control::GaitechPose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_local_control::GaitechPose_<ContainerAllocator> const> ConstPtr;

}; // struct GaitechPose_

typedef ::robot_local_control::GaitechPose_<std::allocator<void> > GaitechPose;

typedef boost::shared_ptr< ::robot_local_control::GaitechPose > GaitechPosePtr;
typedef boost::shared_ptr< ::robot_local_control::GaitechPose const> GaitechPoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_local_control::GaitechPose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_local_control::GaitechPose_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot_local_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'robot_local_control': ['/home/fetch/catkin_ws/src/robot_local_control/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robot_local_control::GaitechPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_local_control::GaitechPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_local_control::GaitechPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_local_control::GaitechPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_local_control::GaitechPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_local_control::GaitechPose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_local_control::GaitechPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b809aeffe83b44060751544686db7c54";
  }

  static const char* value(const ::robot_local_control::GaitechPose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb809aeffe83b4406ULL;
  static const uint64_t static_value2 = 0x0751544686db7c54ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_local_control::GaitechPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_local_control/GaitechPose";
  }

  static const char* value(const ::robot_local_control::GaitechPose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_local_control::GaitechPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 locationX\n\
float64 locationY\n\
float64 orientation\n\
";
  }

  static const char* value(const ::robot_local_control::GaitechPose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_local_control::GaitechPose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.locationX);
      stream.next(m.locationY);
      stream.next(m.orientation);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GaitechPose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_local_control::GaitechPose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_local_control::GaitechPose_<ContainerAllocator>& v)
  {
    s << indent << "locationX: ";
    Printer<double>::stream(s, indent + "  ", v.locationX);
    s << indent << "locationY: ";
    Printer<double>::stream(s, indent + "  ", v.locationY);
    s << indent << "orientation: ";
    Printer<double>::stream(s, indent + "  ", v.orientation);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_LOCAL_CONTROL_MESSAGE_GAITECHPOSE_H
